### PR TITLE
README: added details to generate self-signed cert

### PR DESCRIPTION
**Pull request by matttbe**
Hello,

Thank you for developing this nice privacy and compression proxy :-)

I'm just proposing here to improve the README file and add details about how to generate a self-signed certificate. Every time I have to generate a new key and certificate, I have to find the correct options :-)

I also added a link to the next section: how to validate the self-signed certificate on Firefox? I didn't see these details maybe because I already used Janus Configurator Proxy add-on before and I thought that there was something wrong with my certificate... It was my fault but I hope these new details will help other absent-minded people :-)

Last details: I added the minimal version for Firefox.

If you want, I just created a Dockerfile and a docker repository to quickly build `node-janus` on a container:
- https://github.com/matttbe/docker-janus-node
- https://registry.hub.docker.com/u/matttbe/docker-janus-node/

Have a nice day,

Matt

### CODE REVIEW

**Comment by eamsen** [comment]
Thank you for keeping the README up to date. Let's land this without the explicit OpenSSL documentation.

**Comment by matttbe** [comment]
Thank you for this review!

**Comment by matttbe** [comment]
I guess it's maybe easier for everyone if I split these two commits into two different pull requests!

**Comment by matttbe** [comment]
I just re-push with this text:

> You will also need to generate a new key and a new certificate for your server
> FQDN. Fore more details about that, please have a look to [node-spdyproxy](https://github.com/igrigorik/node-spdyproxy#securing-the-proxy)
> documentation.

What do you think about that?

**Comment by eamsen** [comment]
The readme of another proxy isn't what I would consider a stable link. The official OpenSSL HOWTO's aren't very user friendly however, so I assume your first version of simply putting the command line into this readme is the best choice we have, after all.

Also, for local testing, you don't **have** to create new certificates, you can just use the provided ones.
So we should probably move that info under the deployment section.

Sorry for the trouble, but good documentation is key for promoting collaboration, so thank you for helping out with that!

**Comment by matttbe** [comment]
> The readme of another proxy isn't what I would consider a stable link

Yes, you're right! I just push a new version with a few details (maybe too much?) about how to generate a new certificate with the good `Common Name` attribute and the problem that we can have because this certificate will not be trusted by the browser.

> Sorry for the trouble, but good documentation is key for promoting collaboration, so thank you for helping out with that!

No problem, I understand that maintaining a good documentation is very important ;-)

**Comment by eamsen** [comment]
Yeah, that's a but too detailed, just your first version but under deployment would be good.

**Comment by matttbe** [comment]
Unfortunately, I no longer have this version :-)
(I thought Github kept all versions linked to a pull request as Gerrit does)

Is it better now? :-)

**Comment by matttbe** [comment]
Thank you for you patience :-)

**Comment by eamsen** [comment]
Thank you for your contribution!
Now that you've managed to land a readme update, landing code updates should be cakewalk ;)

**Pull request merged**
